
FIRST_NAME = "firstNameTest"
LAST_NAME = "firstNameTest"
ADDRESS = "addressTest"
VALID_PHONE_NUMBER = "0743256778"
INVALID_PHONE_NUMBER  = "invalidPhone"
INVALID_EMAIL = "invalidEmail"
VALID_EMAIL = "abc@test.com"
VALID_SCHEDULE = "12-10-2023"
INVALID_SCHEDULE = "111111"
VALID_CUSTOMER_ID = 1
INVALID_CUSTOMER_ID = 999
